- instrument/instrument/custom_instrument/delivery_note/delivery_note.py
- instrument/instrument/custom_instrument/purchase_invoice/purchase_invoice.py
- instrument/instrument/custom_instrument/purchase_order/purchase_order.py
- instrument/instrument/custom_instrument/purchase_receipt/purchase_receipt.py
- instrument/instrument/custom_instrument/request_for_quotation/request_for_quotation.py
- instrument/instrument/custom_instrument/sales_invoice/sales_invoice.py
- instrument/instrument/custom_instrument/sales_order/sales_order.py
- instrument/instrument/custom_instrument/supplier_quotation/supplier_quotation.py
[feature][email trigger][custom scripts]
> [feature][email trigger][custom scripts]

- instrument/hooks.py
- instrument/instrument/custom_instrument/item/item.py
- instrument/instrument/custom_instrument/work_order/work_order.py
[Fix][Added validation on item master for default warehouse,check stock of all the warehouses except wip for item stock status on work order]
> [Fix][Added validation on item master for default warehouse,check stock of all the warehouses except wip for item stock status on work order]

- instrument/hooks.py
- instrument/instrument/custom_instrument/bom/bom_list.js
- instrument/instrument/doctype/engineering_revision/engineering_revision_list.js
> Feature-Open Default Eng-Rev and BOM while opening it from document hyperlink

- instrument/hooks.py
- instrument/instrument/custom_instrument/stock_reconciliation/stock_reconciliation.js
- instrument/instrument/custom_instrument/stock_reconciliation/stock_reconciliation.py
Merge Branch : master
[Feature][Add button Fetch Warehouses for Items on Stock Reconciliation]
Current Button "Fetch Items from Warehouse" gets the data based on selected warehouse .
Instead New Button "Fetch Warehouses for Items" gets data based on selected item .
> [Feature][Add button Fetch Warehouses for Items on Stock Reconciliation]

- instrument/instrument/custom_instrument/stock_reconciliation/stock_reconciliation.js
> [Test Pull request Template]

- instrument/instrument/page/new_capacity_to_make/new_capacity_to_make.html
- instrument/instrument/page/new_capacity_to_make/new_capacity_to_make.py
> capacity to make case 1

- instrument/instrument/doctype/consolidated_pick_list/consolidated_pick_list.js
- instrument/instrument/doctype/consolidated_pick_list/consolidated_pick_list.py
- instrument/instrument/doctype/pick_orders/pick_orders.json
> [fix][consilidated pick list]

- instrument/instrument/custom_instrument/bom/bom.py
> [fix][bom submission issue]

- instrument/instrument/doctype/production_planning_with_lead_time/production_planning_with_lead_time.py
[fix][Don't create MR for non stock items planning tool]
> [fix][Don't create MR for non stock items planning tool]

- instrument/instrument/doctype/production_planning_with_lead_time/production_planning_with_lead_time.json
[Feature][Planning tool naming series]
> [Feature][Planning tool naming series]

- instrument/instrument/custom_instrument/bom/bom.py
> [fix][Bom not updating old refernce correctly]

- instrument/instrument/custom_instrument/bom/bom.js
> [fix][bom update issue]

- instrument/instrument/custom_instrument/bom_update_tool/bom_update_tool.py
- instrument/instrument/doctype/consolidated_pick_list/consolidated_pick_list.js
- instrument/instrument/doctype/consolidated_pick_list/consolidated_pick_list.json
- instrument/instrument/doctype/consolidated_pick_list/consolidated_pick_list.py
- instrument/instrument/page/new_capacity_to_make/new_capacity_to_make.py
> bom update issue

- instrument/instrument/custom_instrument/material_request/material_request.py
> [Fix][Status Not Updating Properly on MR]

- instrument/instrument/custom_instrument/material_request/material_request.py
> test commit

- instrument/instrument/doctype/consolidated_pick_list/consolidated_pick_list.js
- instrument/instrument/doctype/consolidated_pick_list/consolidated_pick_list.py
- instrument/instrument/doctype/pick_orders/pick_orders.json
- instrument/instrument/doctype/work_order_pick_list_item/work_order_pick_list_item.json
Right now, it seems like FV010180 is incorrectly calculating the qty required in the following row. For example, we think that qty should be 5 in row 23, and 3 in row 63.
> [Fix][TASK-2023-00086]

- instrument/instrument/doctype/production_planning_with_lead_time/production_planning_with_lead_time.py
> [fix][production planning with lead time filters

- instrument/hooks.py
- instrument/instrument/doctype/production_planning_with_lead_time/production_planning_with_lead_time.js
- instrument/instrument/doctype/production_planning_with_lead_time/production_planning_with_lead_time.py
> [Fix][Planning tool fixes,serial no series disabled

- instrument/instrument/page/new_capacity_to_make/new_capacity_to_make.html
- instrument/instrument/page/new_capacity_to_make/new_capacity_to_make.js
- instrument/instrument/page/new_capacity_to_make/new_capacity_to_make.py
> [Feature][Capacity To Make]

- instrument/instrument/doctype/production_planning_with_lead_time/production_planning_with_lead_time.py
> [Fix][Double booking of qty against sales order on planning tool]

- instrument/instrument/doctype/consolidated_pick_list/consolidated_pick_list.py
> [Fix][Consolidated Pick List Excel Export]

- instrument/instrument/custom_instrument/stock_entry/stock_entry.py
- instrument/instrument/doctype/consolidated_pick_list/consolidated_pick_list.py
> [Fix][Consolidated Pick List

- instrument/instrument/doctype/consolidated_pick_list/consolidated_pick_list.py
> [fix][consolidated pick list]

- instrument/instrument/report/work_order_explorer/work_order_explorer.js
- instrument/instrument/report/work_order_explorer/work_order_explorer.json
- instrument/instrument/report/work_order_explorer/work_order_explorer.py
> [Feature][Work ORder Explorer Report]

- instrument/hooks.py
- instrument/instrument/custom_instrument/purchase_order/purchase_order.py
- instrument/instrument/custom_instrument/purchase_order/purchase_order_list.js
> [Feature][TASK-2023-00079-Enhancement to Purchase Order List]

- instrument/instrument/doctype/consolidated_pick_list/consolidated_pick_list.py
- instrument/instrument/doctype/pick_list_sales_order_table/pick_list_sales_order_table.json
- instrument/instrument/doctype/sales_order_pick_list_table/sales_order_pick_list_table.json
> [fix][Consolidated pick list - subcontracting purchase orders]

- instrument/instrument/doctype/consolidated_pick_list/consolidated_pick_list.js
- instrument/instrument/doctype/consolidated_pick_list/consolidated_pick_list.py
- instrument/instrument/doctype/pick_list_sales_order_table/pick_list_sales_order_table.json
- instrument/instrument/doctype/sales_order_pick_list_item/sales_order_pick_list_item.json
> [fix][Conslidated pick list -sales order fulfillment

- instrument/hooks.py
- instrument/instrument/doctype/consolidated_pick_list/consolidated_pick_list.js
- instrument/instrument/doctype/consolidated_pick_list/consolidated_pick_list.json
- instrument/instrument/doctype/consolidated_pick_list/consolidated_pick_list.py
> [Feature][Allow completion of job card in consolidated pick list]

- instrument/instrument/page/new_capacity_to_make/new_capacity_to_make.py
> [Feature][Export Excel - Capacity to make]

- instrument/instrument/custom_instrument/stock_reconciliation/stock_reconciliation.js
- instrument/instrument/page/new_capacity_to_make/new_capacity_to_make.js
- instrument/instrument/page/new_capacity_to_make/new_capacity_to_make.py
> [Fix][Capacity to make]

- instrument/instrument/page/new_capacity_to_make/new_capacity_to_make.py
> [Feature][API-Capacity to plan]

- instrument/instrument/doctype/consolidated_pick_list/consolidated_pick_list.py
- instrument/instrument/doctype/production_planning_with_lead_time/production_planning_with_lead_time.py
> [Fix & Feature][Planning tool,Consolidated Pick List]

- instrument/instrument/custom_instrument/material_request/material_request.py
- instrument/instrument/doctype/consolidated_pick_list/consolidated_pick_list.py
- instrument/instrument/doctype/production_planning_with_lead_time/production_planning_with_lead_time.js
- instrument/instrument/doctype/production_planning_with_lead_time/production_planning_with_lead_time.py
> [Feature][Enhancements to Create Button in Materil Request ]

- instrument/instrument/page/new_capacity_to_make/new_capacity_to_make.py
> [Fix][Capacity to make api]

- instrument/instrument/doctype/package_document/package_document.js
- instrument/instrument/doctype/package_document/package_document.py
> [Feature][Download Zipped Copies of Engineering Packages]

- instrument/instrument/page/new_capacity_to_make/new_capacity_to_make.py
> [fix][capacity-code optimization]

- instrument/hooks.py
- instrument/instrument/page/new_capacity_to_make/new_capacity_to_make.py
> [fix][bom creation tool

- instrument/instrument/page/new_capacity_to_make/new_capacity_to_make.py
> [Capacity fix][]

- instrument/instrument/doctype/production_planning_with_lead_time/production_planning_with_lead_time.py
> [planning tool fix]

- instrument/hooks.py
- instrument/instrument/custom_instrument/purchase_order/purchase_order.py
- instrument/instrument/custom_instrument/work_order/work_order.py
- instrument/instrument/doctype/consolidated_pick_list/consolidated_pick_list.js
- instrument/instrument/doctype/consolidated_pick_list/consolidated_pick_list.json
- instrument/instrument/doctype/consolidated_pick_list/consolidated_pick_list.py
- instrument/instrument/doctype/production_planning_with_lead_time/production_planning_with_lead_time.py
- instrument/instrument/doctype/production_planning_with_lead_time/production_planning_with_lead_time_dashboard.py
- instrument/instrument/doctype/work_order_unstock_items/work_order_unstock_items.json
> [fix&feature][Consolidated pick list & planning tool]

- instrument/instrument/custom_instrument/delivery_note/delivery_note.py
- instrument/instrument/custom_instrument/material_request/material_request.py
- instrument/instrument/custom_instrument/purchase_order/purchase_order.py
- instrument/instrument/doctype/consolidated_pick_list/consolidated_pick_list.js
- instrument/instrument/doctype/consolidated_pick_list/consolidated_pick_list.json
- instrument/instrument/doctype/consolidated_pick_list/consolidated_pick_list.py
- instrument/instrument/doctype/pick_list_sales_order_table/pick_list_sales_order_table.json
> [Fix&feature][Consolidated pick list]

- instrument/instrument/doctype/bom_creation_tool/bom_creation_tool.json
- instrument/instrument/doctype/difference_in_review_item_mappings_table/difference_in_review_item_mappings_table.json
- instrument/instrument/doctype/table_of_standard_boms_produced/table_of_standard_boms_produced.json
> Removed Custom

- instrument/instrument/doctype/bom_item_replacement_tool/bom_item_replacement_tool.py
> propogate update to descendent boms

- instrument/instrument/doctype/package_document/package_document.js
> [package doc issue

- instrument/instrument/doctype/package_document/package_document.js
- instrument/instrument/doctype/package_document/package_document.py
> Package doc issues

- instrument/instrument/custom_api.py
> [Feature][Item Maintain stock API Change]

- instrument/hooks.py
- instrument/instrument/custom_instrument/stock_entry/stock_entry.py
- instrument/instrument/doctype/consolidated_pick_list/consolidated_pick_list.py
- instrument/instrument/doctype/production_planning_with_lead_time/production_planning_with_lead_time.py
> [Fix][Version upgrade fixes]

- instrument/instrument/custom_instrument/work_order_pick_list/work_order_pick_list.py
- instrument/instrument/doctype/work_order_pick_list/work_order_pick_list.json
- instrument/instrument/doctype/work_order_pick_list/work_order_pick_list.py
> [fix][doctype removed]

- instrument/instrument/doctype/production_planning_with_lead_time/production_planning_with_lead_time.py
> [Fix][Planning tool]

- instrument/instrument/custom_instrument/batch/batch.py
- instrument/instrument/custom_instrument/item/item.py
- instrument/instrument/custom_instrument/job_card/job_card.py
- instrument/instrument/custom_instrument/pick_list/pick_list.py
- instrument/instrument/custom_instrument/stock_entry/stock_entry.py
- instrument/instrument/custom_instrument/work_order/work_order.py
- instrument/instrument/page/capacity_to_make/capacity_to_make.py
- instrument/instrument/page/new_capacity_to_make/new_capacity_to_make.py
> [Fix][Library issue]

- instrument/instrument/doctype/consolidated_pick_list/consolidated_pick_list.py
> [Fix][batch issue]

- instrument/instrument/custom_instrument/item/item.py
- instrument/instrument/custom_instrument/purchase_order/purchase_order.py
- instrument/instrument/doctype/consolidated_pick_list/consolidated_pick_list.py
> [Fix][Serial no issue]

- instrument/instrument/custom_instrument/item/item.py
> [Fix][Item]

- instrument/instrument/report/pending_bom_creation_tool/pending_bom_creation_tool.js
- instrument/instrument/report/pending_bom_creation_tool/pending_bom_creation_tool.json
- instrument/instrument/report/pending_bom_creation_tool/pending_bom_creation_tool.py
> pending bom creation tool report added

- instrument/instrument/custom_instrument/material_request/material_request.py
> [Fix][Error on mr while creating po]

- instrument/instrument/report/bom_needs_to_be_updated/bom_needs_to_be_updated.py
> [Fix][Allow only default boms in report]

- instrument/instrument/custom_instrument/sales_invoice/sales_invoice.py
> [Fix][Sales Invoice Class override]

- instrument/instrument/custom_api.py
> [Fix][API issue]

- instrument/hooks.py
- instrument/instrument/custom_instrument/payment_entry/payment_entry.py
> [Fix][API intergration payment entry issue]

- instrument/instrument/doctype/package_document/package_document.js
> [Removed button Copy attachments from side bar]

- instrument/instrument/page/new_capacity_to_make/new_capacity_to_make.py
> [Fix][Capacity to make doctype error]

- instrument/instrument/doctype/package_document/package_document.js
> [Package doc changes]

- instrument/instrument/custom_instrument/bom/bom.js
- instrument/instrument/doctype/mapped_bom/mapped_bom.js
- instrument/instrument/doctype/mapped_bom/mapped_bom.json
> [Fix][Duplicate BOM to Mapped BOM button issue]

- instrument/instrument/custom_instrument/bom/bom_tree.js
- instrument/instrument/doctype/bom_creation_tool/bom_creation_tool.py
> [Fix][BOM Creation Tool]

- instrument/instrument/doctype/consolidated_pick_list/consolidated_pick_list.js
- instrument/instrument/doctype/consolidated_pick_list/consolidated_pick_list.json
- instrument/instrument/doctype/consolidated_pick_list/consolidated_pick_list.py
> [Fix][Issues regarding consolidated pick list]

- instrument/hooks.py
- instrument/instrument/doctype/consolidated_pick_list/consolidated_pick_list.js
- instrument/instrument/doctype/consolidated_pick_list/consolidated_pick_list.json
- instrument/instrument/doctype/consolidated_pick_list/consolidated_pick_list.py
- instrument/instrument/doctype/pick_list_work_orders/pick_list_work_orders.json
- instrument/instrument/doctype/pick_list_work_orders/pick_list_work_orders.py
- instrument/instrument/doctype/pick_work_orders/pick_work_orders.json
- instrument/instrument/doctype/pick_work_orders/pick_work_orders.py
> [Feature][Consolidated pick list enhancements]

- instrument/instrument/report/traceability_report/traceability_report.js
- instrument/instrument/report/traceability_report/traceability_report.json
- instrument/instrument/report/traceability_report/traceability_report.py
> report changes

- instrument/instrument/report/traceability_report/traceability_report.js
- instrument/instrument/report/traceability_report/traceability_report.py
> report minor corrections

- instrument/hooks.py
- instrument/instrument/custom_instrument/material_request/material_request.py
- instrument/instrument/custom_instrument/purchase_receipt/purchase_receipt.py
- instrument/instrument/custom_instrument/stock_entry/stock_entry.py
- instrument/instrument/doctype/consolidated_pick_list/consolidated_pick_list.js
- instrument/instrument/doctype/consolidated_pick_list/consolidated_pick_list.py
> [Feature][Consolidated pick list changes]

- instrument/instrument/custom_instrument/stock_entry/stock_entry.py
- instrument/instrument/doctype/consolidated_pick_list/consolidated_pick_list.py
> [Fix][Consolidated pick list changes]

- instrument/instrument/report/backward_traceability/backward_traceability.js
- instrument/instrument/report/backward_traceability/backward_traceability.json
- instrument/instrument/report/backward_traceability/backward_traceability.py
- instrument/instrument/report/forward_traceability/forward_traceability.py
> forward report changes

- instrument/instrument/doctype/api_response_log/api_response_log.js
- instrument/instrument/doctype/api_response_log/api_response_log.json
- instrument/instrument/doctype/api_response_log/api_response_log.py
- instrument/instrument/doctype/api_response_log/test_api_response_log.py
- instrument/instrument/doctype/supplier_quotation_comparison_tool/supplier_quotation_comparison_tool.js
- instrument/instrument/page/new_capacity_to_make/new_capacity_to_make.html
- instrument/instrument/page/new_capacity_to_make/new_capacity_to_make.py
> API response store added

- instrument/instrument/report/backward_traceability/backward_traceability.py
> new report changes

- instrument/instrument/report/backward_traceability/backward_traceability.py
- instrument/instrument/report/forward_traceability/forward_traceability.py
> forward tracebility report changes
